using System.Net;
using System.Text;
using SpecHygiene.Models;

namespace SpecHygiene.Reporters;

/// <summary>
/// Self-contained HTML report for a SpecHygiene run. One file, inline CSS, no external assets and no
/// JavaScript — collapsible sections use native &lt;details&gt;, so it stays safe to email or open
/// offline. Renders only the four static checks; nothing here talks to a network or an API.
/// </summary>
public sealed class HtmlReporter : IReporter
{
    public string OutputFileName => "spechygiene-report.html";

    public Task GenerateAsync(DuplicateAnalysisReport report, string outputDirectory)
    {
        var sb = new StringBuilder();
        sb.Append("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">");
        sb.Append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
        sb.Append("<title>SpecHygiene report</title>");
        sb.Append("<style>").Append(Css).Append("</style></head><body><main>");

        AppendDashboard(sb, report);

        if (report.UnusedCodeReport is { } dead) AppendUnusedCode(sb, dead);
        if (report.StepDefinitionCoverage is { } cov) AppendUnusedSteps(sb, cov);
        AppendDataErrors(sb, report);
        AppendDuplicates(sb, report);

        sb.Append("<footer>Generated by <strong>SpecHygiene</strong> — static hygiene checks for Reqnroll / SpecFlow. No AI, no network.</footer>");
        sb.Append("</main></body></html>");

        Directory.CreateDirectory(outputDirectory);
        var path = Path.Combine(outputDirectory, OutputFileName);
        File.WriteAllText(path, sb.ToString());
        Console.WriteLine($"HTML report: {Path.GetFullPath(path)}");
        return Task.CompletedTask;
    }

    // ------------------------------------------------------------------ dashboard

    private static void AppendDashboard(StringBuilder sb, DuplicateAnalysisReport r)
    {
        var dead = r.UnusedCodeReport is { } d ? d.UnusedMethods.Count + d.UnusedClasses.Count + d.UnusedInterfaces.Count : 0;
        var steps = r.StepDefinitionCoverage?.UnusedDefinitions.Count ?? 0;
        var errors = r.DataErrors.Count;
        var dupes = r.ScenarioDuplicates.Count;
        var total = dead + steps + errors + dupes;

        sb.Append("<header>");
        sb.Append("<div class=\"top\">");
        sb.Append("<div class=\"brand\"><span class=\"logo\">◈</span><div><h1>SpecHygiene</h1>");
        sb.Append("<span class=\"tagline\">Reqnroll / SpecFlow hygiene report</span></div></div>");
        var overall = total == 0 ? "ok" : (errors > 0 ? "bad" : "warn");
        var overallText = total == 0 ? "All clean" : $"{total} finding{(total == 1 ? "" : "s")}";
        sb.Append($"<span class=\"status {overall}\">{E(overallText)}</span>");
        sb.Append("</div>");
        sb.Append($"<p class=\"scan\">Scanned {r.FeatureFilesScanned} feature file(s) · {r.TotalScenariosAnalyzed} scenario(s) · {r.TotalStepsAnalyzed} step(s)<span class=\"dot\">·</span>{E(r.GeneratedAt.ToString("yyyy-MM-dd HH:mm"))}</p>");

        sb.Append("<div class=\"dash\">");
        Metric(sb, IconCode, dead, "Unused code", dead == 0 ? "ok" : "warn", "#unused-code");
        Metric(sb, IconSteps, steps, "Unused step defs", steps == 0 ? "ok" : "warn", "#unused-steps");
        Metric(sb, IconData, errors, "Data errors", errors == 0 ? "ok" : "bad", "#data-errors");
        Metric(sb, IconDup, dupes, "Duplicates", dupes == 0 ? "ok" : "warn", "#duplicates");
        sb.Append("</div></header>");
    }

    private static void Metric(StringBuilder sb, string icon, int n, string label, string cls, string href)
    {
        sb.Append($"<a class=\"metric {cls}\" href=\"{href}\">");
        sb.Append($"<span class=\"mi\">{icon}</span>");
        sb.Append("<span class=\"mt\">");
        sb.Append($"<span class=\"n\">{n}</span><span class=\"l\">{E(label)}</span>");
        sb.Append("</span>");
        sb.Append($"<span class=\"mstat\">{(n == 0 ? "clean" : "review")}</span>");
        sb.Append("</a>");
    }

    // ------------------------------------------------------------------ sections

    private static void AppendUnusedCode(StringBuilder sb, UnusedCodeReport dead)
    {
        var total = dead.UnusedMethods.Count + dead.UnusedClasses.Count + dead.UnusedInterfaces.Count;
        Open(sb, "unused-code", IconCode, "Unused code", total,
            $"{total} element(s) with no references · scanned {dead.TotalMethodsScanned} method(s), {dead.TotalClassesScanned} class(es), {dead.TotalInterfacesScanned} interface(s)");
        if (total == 0) { Clean(sb, "No dead code found."); return; }

        sb.Append("<table><thead><tr><th>Kind</th><th>Element</th><th>Containing type</th><th>Visibility</th><th>Location</th></tr></thead><tbody>");
        foreach (var e in dead.UnusedMethods.Concat(dead.UnusedClasses).Concat(dead.UnusedInterfaces))
        {
            sb.Append("<tr>");
            sb.Append($"<td>{Tag(e.ElementType.ToString())}</td>");
            sb.Append($"<td class=\"mono strong\">{E(e.Name)}</td>");
            sb.Append($"<td class=\"mono dim\">{E(e.ContainingType)}</td>");
            sb.Append($"<td>{E(e.Visibility)}</td>");
            sb.Append($"<td class=\"mono dim\">{E(ShortPath(e.FilePath))}:{e.LineNumber}</td>");
            sb.Append("</tr>");
        }
        sb.Append("</tbody></table>");
        Close(sb);
    }

    private static void AppendUnusedSteps(StringBuilder sb, StepDefinitionCoverageReport cov)
    {
        Open(sb, "unused-steps", IconSteps, "Unused step definitions", cov.UnusedDefinitions.Count,
            $"Coverage {cov.CoveragePercentage:F1}% · {cov.UsedStepDefinitions}/{cov.TotalStepDefinitions} bindings used · {cov.UnusedDefinitions.Count} unused");
        if (cov.UnusedDefinitions.Count == 0) { Clean(sb, "Every step definition is used by at least one scenario."); return; }

        sb.Append("<table><thead><tr><th>Kind</th><th>Pattern</th><th>Method</th><th>Location</th></tr></thead><tbody>");
        foreach (var d in cov.UnusedDefinitions)
        {
            sb.Append("<tr>");
            sb.Append($"<td>{Tag(d.Type.ToString())}</td>");
            sb.Append($"<td class=\"mono strong\">{E(d.Pattern)}</td>");
            sb.Append($"<td class=\"mono dim\">{E(d.ClassName)}.{E(d.MethodName)}</td>");
            sb.Append($"<td class=\"mono dim\">{E(ShortPath(d.FilePath))}:{d.LineNumber}</td>");
            sb.Append("</tr>");
        }
        sb.Append("</tbody></table>");
        Close(sb);
    }

    private static void AppendDataErrors(StringBuilder sb, DuplicateAnalysisReport r)
    {
        Open(sb, "data-errors", IconData, "Data errors", r.DataErrors.Count, $"{r.DataErrors.Count} feature-file issue(s)");
        if (r.DataErrors.Count == 0) { Clean(sb, "No data errors."); return; }

        foreach (var group in r.DataErrors.GroupBy(e => e.ErrorType))
        {
            sb.Append($"<h3>{E(Humanize(group.Key.ToString()))}<span class=\"count\">{group.Count()}</span></h3>");
            sb.Append("<table><thead><tr><th>Scenario</th><th>Detail</th><th>Location</th></tr></thead><tbody>");
            foreach (var e in group)
            {
                var detail = e.UndefinedPlaceholders.Count > 0
                    ? "Undefined: " + string.Join(", ", e.UndefinedPlaceholders.Select(p => "&lt;" + E(p) + "&gt;"))
                    : E(e.StepText);
                sb.Append("<tr>");
                sb.Append($"<td>{E(e.Scenario)}</td>");
                sb.Append($"<td class=\"mono\">{detail}</td>");
                sb.Append($"<td class=\"mono dim\">{E(e.FeatureFile)}:{e.LineNumber}</td>");
                sb.Append("</tr>");
            }
            sb.Append("</tbody></table>");
        }
        Close(sb);
    }

    private static void AppendDuplicates(StringBuilder sb, DuplicateAnalysisReport r)
    {
        var groups = r.ScenarioDuplicates;
        Open(sb, "duplicates", IconDup, "Duplicate scenarios", groups.Count,
            $"{groups.Count} duplicate / near-duplicate scenario group(s)");

        if (groups.Count == 0) { Clean(sb, "No duplicate scenarios found."); return; }

        // Each row is a base scenario and a scenario it duplicates/overlaps, with both locations and
        // the match type (Exact / Superset / Subset / near-duplicate) and overlap %.
        sb.Append("<table><thead><tr><th>Type</th><th>Scenario</th><th>Duplicates / overlaps</th><th>Overlap</th></tr></thead><tbody>");
        foreach (var g in groups)
            foreach (var m in g.Matches)
            {
                sb.Append("<tr>");
                sb.Append($"<td>{Tag(g.DuplicateType.ToString())}</td>");
                sb.Append($"<td class=\"strong\">{E(g.BaseScenario.ScenarioName)}<br><span class=\"dim mono sm\">{E(g.BaseScenario.FeatureFile)}:{g.BaseScenario.ScenarioLineNumber}</span></td>");
                sb.Append($"<td class=\"strong\">{E(m.Scenario.ScenarioName)}<br><span class=\"dim mono sm\">{E(m.Scenario.FeatureFile)}:{m.Scenario.ScenarioLineNumber}</span></td>");
                sb.Append($"<td class=\"strong\">{m.OverlapPercentage:F0}%</td>");
                sb.Append("</tr>");
            }
        sb.Append("</tbody></table>");
        Close(sb);
    }

    // ------------------------------------------------------------------ helpers

    // A collapsible section. Open by default when it has findings; collapsed when clean.
    private static void Open(StringBuilder sb, string id, string icon, string title, int count, string sub)
    {
        var status = count == 0 ? "ok" : (id == "data-errors" ? "bad" : "warn");
        sb.Append($"<details id=\"{id}\" class=\"check {status}\"{(count > 0 ? " open" : "")}>");
        sb.Append("<summary>");
        sb.Append($"<span class=\"chev\">{IconChevron}</span>");
        sb.Append($"<span class=\"si\">{icon}</span>");
        sb.Append($"<span class=\"stitle\">{E(title)}</span>");
        sb.Append($"<span class=\"pill\">{count}</span>");
        sb.Append($"<span class=\"ssub\">{E(sub)}</span>");
        sb.Append("</summary><div class=\"body\">");
    }

    private static void Close(StringBuilder sb) => sb.Append("</div></details>");

    private static void Clean(StringBuilder sb, string msg)
    {
        sb.Append($"<p class=\"clean\"><span class=\"dotok\"></span>{E(msg)}</p>");
        Close(sb);
    }

    private static string Tag(string s) => $"<span class=\"tag\">{E(s)}</span>";
    private static string E(string? s) => WebUtility.HtmlEncode(s ?? "");

    private static string ShortPath(string path)
    {
        if (string.IsNullOrEmpty(path)) return "";
        var parts = path.Replace('\\', '/').Split('/');
        return parts.Length <= 2 ? path : string.Join("/", parts[^2..]);
    }

    private static string Humanize(string pascal)
    {
        var sb = new StringBuilder();
        for (int i = 0; i < pascal.Length; i++)
        {
            if (i > 0 && char.IsUpper(pascal[i])) sb.Append(' ');
            sb.Append(i == 0 ? char.ToUpperInvariant(pascal[i]) : char.ToLowerInvariant(pascal[i]));
        }
        return sb.ToString();
    }

    // Feather-style inline icons (monochrome, currentColor).
    private const string IconCode = "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m8 6-6 6 6 6M16 6l6 6-6 6\"/></svg>";
    private const string IconSteps = "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M9 6h11M9 12h11M9 18h11M4 6h.01M4 12h.01M4 18h.01\"/></svg>";
    private const string IconData = "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M10.3 3.9 1.8 18a2 2 0 0 0 1.7 3h17a2 2 0 0 0 1.7-3L13.7 3.9a2 2 0 0 0-3.4 0z\"/><path d=\"M12 9v4M12 17h.01\"/></svg>";
    private const string IconDup = "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"9\" y=\"9\" width=\"11\" height=\"11\" rx=\"2\"/><path d=\"M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1\"/></svg>";
    private const string IconChevron = "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m9 18 6-6-6-6\"/></svg>";

    private const string Css = """
        :root {
          --bg:#0d1117; --panel:#141b26; --panel2:#0f1620; --line:#232d3d; --txt:#e7ebf2; --dim:#8b95a9;
          --accent:#5aa9f2; --ok:#3fb950; --warn:#e3a008; --bad:#f0517a;
          --shadow:0 1px 0 rgba(255,255,255,.02), 0 8px 24px rgba(0,0,0,.25);
        }
        * { box-sizing:border-box; }
        html { scroll-behavior:smooth; }
        body { margin:0; background:var(--bg); color:var(--txt);
               font:15px/1.55 -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif; }
        main { max-width:1080px; margin:0 auto; padding:0 22px 60px; }

        /* ---- dashboard ---- */
        header { padding:36px 0 8px; }
        .top { display:flex; align-items:center; justify-content:space-between; gap:16px; flex-wrap:wrap; }
        .brand { display:flex; align-items:center; gap:14px; }
        .logo { width:44px; height:44px; display:grid; place-items:center; border-radius:12px;
                background:linear-gradient(135deg,#1d4ed8,#0891b2); color:#fff; font-size:22px; box-shadow:var(--shadow); }
        h1 { margin:0; font-size:24px; letter-spacing:-.4px; }
        .tagline { color:var(--dim); font-size:13px; }
        .status { padding:7px 14px; border-radius:999px; font-size:13px; font-weight:700; border:1px solid transparent; }
        .status.ok  { color:var(--ok);  background:rgba(63,185,80,.10);  border-color:rgba(63,185,80,.30); }
        .status.warn{ color:var(--warn);background:rgba(227,160,8,.10);  border-color:rgba(227,160,8,.30); }
        .status.bad { color:var(--bad); background:rgba(240,81,122,.10); border-color:rgba(240,81,122,.30); }
        .scan { color:var(--dim); font-size:13px; margin:14px 0 22px; }
        .scan .dot { margin:0 8px; opacity:.5; }

        .dash { display:grid; grid-template-columns:repeat(auto-fit,minmax(210px,1fr)); gap:14px; }
        .metric { display:flex; align-items:center; gap:14px; text-decoration:none; color:inherit;
                  background:var(--panel); border:1px solid var(--line); border-radius:14px; padding:16px 18px;
                  box-shadow:var(--shadow); transition:transform .12s ease, border-color .12s ease; position:relative; overflow:hidden; }
        .metric::before { content:""; position:absolute; left:0; top:0; bottom:0; width:4px; background:var(--dim); }
        .metric.ok::before { background:var(--ok); } .metric.warn::before { background:var(--warn); } .metric.bad::before { background:var(--bad); }
        .metric:hover { transform:translateY(-2px); border-color:#31405a; }
        .mi { width:38px; height:38px; flex:0 0 auto; display:grid; place-items:center; border-radius:10px;
              background:var(--panel2); color:var(--accent); }
        .metric.ok .mi { color:var(--ok); } .metric.warn .mi { color:var(--warn); } .metric.bad .mi { color:var(--bad); }
        .mi svg { width:20px; height:20px; }
        .mt { display:flex; flex-direction:column; line-height:1.1; margin-right:auto; }
        .mt .n { font-size:28px; font-weight:800; letter-spacing:-.5px; }
        .mt .l { color:var(--dim); font-size:12.5px; margin-top:3px; }
        .mstat { font-size:11px; font-weight:700; text-transform:uppercase; letter-spacing:.6px; color:var(--dim); align-self:flex-start; }
        .metric.ok .mstat { color:var(--ok); } .metric.warn .mstat { color:var(--warn); } .metric.bad .mstat { color:var(--bad); }

        /* ---- collapsible checks ---- */
        .check { background:var(--panel); border:1px solid var(--line); border-radius:14px; margin-top:18px;
                 box-shadow:var(--shadow); overflow:hidden; }
        summary { list-style:none; cursor:pointer; display:flex; align-items:center; gap:12px; padding:16px 18px;
                  user-select:none; }
        summary::-webkit-details-marker { display:none; }
        summary:hover { background:rgba(255,255,255,.015); }
        .chev { color:var(--dim); display:grid; place-items:center; transition:transform .18s ease; }
        .chev svg { width:16px; height:16px; }
        .check[open] > summary .chev { transform:rotate(90deg); }
        .si { width:30px; height:30px; display:grid; place-items:center; border-radius:8px; background:var(--panel2); color:var(--accent); flex:0 0 auto; }
        .check.ok .si { color:var(--ok); } .check.warn .si { color:var(--warn); } .check.bad .si { color:var(--bad); }
        .si svg { width:17px; height:17px; }
        .stitle { font-size:16px; font-weight:700; }
        .pill { min-width:24px; text-align:center; padding:2px 9px; border-radius:999px; font-size:12.5px; font-weight:700;
                background:var(--panel2); border:1px solid var(--line); color:var(--dim); }
        .check.warn .pill { color:var(--warn); border-color:rgba(227,160,8,.35); }
        .check.bad .pill  { color:var(--bad);  border-color:rgba(240,81,122,.35); }
        .check.ok .pill   { color:var(--ok);   border-color:rgba(63,185,80,.30); }
        .ssub { color:var(--dim); font-size:12.5px; margin-left:auto; text-align:right; }
        .body { padding:4px 18px 20px; border-top:1px solid var(--line); }

        h3 { margin:20px 0 6px; font-size:12px; color:var(--dim); text-transform:uppercase; letter-spacing:.7px; display:flex; align-items:center; gap:8px; }
        h3 .count { color:var(--txt); background:var(--panel2); border:1px solid var(--line); border-radius:999px; padding:1px 8px; font-size:11px; }

        table { width:100%; border-collapse:collapse; margin-top:10px; font-size:13.5px; display:block; overflow-x:auto; }
        thead th { text-align:left; color:var(--dim); font-weight:600; font-size:12px; text-transform:uppercase; letter-spacing:.4px;
                   border-bottom:1px solid var(--line); padding:9px 12px; white-space:nowrap; }
        tbody td { padding:11px 12px; border-bottom:1px solid var(--line); vertical-align:top; }
        tbody tr:last-child td { border-bottom:0; }
        tbody tr:hover { background:rgba(90,169,242,.05); }
        .mono { font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; font-size:12.5px; }
        .sm { font-size:11.5px; } .strong { font-weight:600; } .dim { color:var(--dim); }
        .tag { display:inline-block; background:var(--panel2); color:var(--accent); border:1px solid var(--line);
               border-radius:6px; padding:2px 8px; font-size:11px; font-weight:700; }
        .clean { display:flex; align-items:center; gap:10px; color:var(--dim); padding:14px 2px 6px; font-size:14px; }
        .dotok { width:9px; height:9px; border-radius:50%; background:var(--ok); box-shadow:0 0 0 3px rgba(63,185,80,.15); flex:0 0 auto; }

        footer { color:var(--dim); font-size:12.5px; text-align:center; margin-top:46px; padding-top:22px; border-top:1px solid var(--line); }

        @media (prefers-color-scheme:light) {
          :root { --bg:#f6f8fb; --panel:#ffffff; --panel2:#f1f4f9; --line:#e4e9f0; --txt:#101828; --dim:#697488;
                  --shadow:0 1px 2px rgba(16,24,40,.04), 0 6px 18px rgba(16,24,40,.06); }
          tbody tr:hover { background:rgba(29,78,216,.04); }
        }
        @media (max-width:640px) { .ssub { display:none; } }
        """;
}
