using System.Net;
using System.Text;
using SpecHygiene.Models;

namespace SpecHygiene.Reporters;

/// <summary>
/// Self-contained HTML report for a SpecHygiene run. One file, inline CSS, no external assets, no
/// JavaScript — safe to email or open offline. Renders only the four static checks; nothing here
/// talks to a network or an API.
/// </summary>
public sealed class HtmlReporter : IReporter
{
    public string OutputFileName => "spechygiene-report.html";

    public Task GenerateAsync(DuplicateAnalysisReport report, string outputDirectory)
    {
        var sb = new StringBuilder();
        sb.Append("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">");
        sb.Append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
        sb.Append("<title>SpecHygiene report</title>");
        sb.Append("<style>").Append(Css).Append("</style></head><body>");

        AppendHeader(sb, report);

        if (report.UnusedCodeReport is { } dead) AppendUnusedCode(sb, dead);
        if (report.StepDefinitionCoverage is { } cov) AppendUnusedSteps(sb, cov);
        if (report.DataErrors.Count > 0 || report.AllScenarios.Count > 0) AppendDataErrors(sb, report);
        AppendDuplicates(sb, report);

        sb.Append("<footer>Generated by <strong>SpecHygiene</strong> — static hygiene checks for Reqnroll / SpecFlow. No AI, no network.</footer>");
        sb.Append("</body></html>");

        Directory.CreateDirectory(outputDirectory);
        var path = Path.Combine(outputDirectory, OutputFileName);
        File.WriteAllText(path, sb.ToString());
        Console.WriteLine($"HTML report: {Path.GetFullPath(path)}");
        return Task.CompletedTask;
    }

    private static void AppendHeader(StringBuilder sb, DuplicateAnalysisReport r)
    {
        var deadCount = r.UnusedCodeReport is { } d ? d.UnusedMethods.Count + d.UnusedClasses.Count + d.UnusedInterfaces.Count : 0;
        var unusedSteps = r.StepDefinitionCoverage?.UnusedDefinitions.Count ?? 0;
        var dupCount = r.ScenarioDuplicates.Count + r.CrossProjectDuplicates.Count + r.WithinProjectDuplicates.Count;

        sb.Append("<header><h1>SpecHygiene</h1>");
        sb.Append($"<p class=\"sub\">Scanned {r.FeatureFilesScanned} feature file(s), {r.TotalScenariosAnalyzed} scenario(s), {r.TotalStepsAnalyzed} step(s) · {E(r.GeneratedAt.ToString("yyyy-MM-dd HH:mm"))}</p>");
        sb.Append("<div class=\"cards\">");
        Card(sb, deadCount, "Unused code", deadCount == 0 ? "ok" : "warn");
        Card(sb, unusedSteps, "Unused step defs", unusedSteps == 0 ? "ok" : "warn");
        Card(sb, r.DataErrors.Count, "Data errors", r.DataErrors.Count == 0 ? "ok" : "bad");
        Card(sb, dupCount, "Duplicates", dupCount == 0 ? "ok" : "warn");
        sb.Append("</div></header>");
    }

    private static void Card(StringBuilder sb, int n, string label, string cls) =>
        sb.Append($"<div class=\"card {cls}\"><span class=\"n\">{n}</span><span class=\"l\">{E(label)}</span></div>");

    private static void AppendUnusedCode(StringBuilder sb, UnusedCodeReport dead)
    {
        var total = dead.UnusedMethods.Count + dead.UnusedClasses.Count + dead.UnusedInterfaces.Count;
        Section(sb, "unused-code", "Unused code",
            $"{total} element(s) with no references · scanned {dead.TotalMethodsScanned} method(s), {dead.TotalClassesScanned} class(es), {dead.TotalInterfacesScanned} interface(s)");
        if (total == 0) { Empty(sb, "No dead code found."); return; }

        sb.Append("<table><thead><tr><th>Kind</th><th>Element</th><th>Containing type</th><th>Visibility</th><th>Location</th></tr></thead><tbody>");
        foreach (var e in dead.UnusedMethods.Concat(dead.UnusedClasses).Concat(dead.UnusedInterfaces))
        {
            sb.Append("<tr>");
            sb.Append($"<td><span class=\"tag\">{E(e.ElementType.ToString())}</span></td>");
            sb.Append($"<td class=\"mono\">{E(e.Name)}</td>");
            sb.Append($"<td class=\"mono dim\">{E(e.ContainingType)}</td>");
            sb.Append($"<td>{E(e.Visibility)}</td>");
            sb.Append($"<td class=\"mono dim\">{E(ShortPath(e.FilePath))}:{e.LineNumber}</td>");
            sb.Append("</tr>");
        }
        sb.Append("</tbody></table></section>");
    }

    private static void AppendUnusedSteps(StringBuilder sb, StepDefinitionCoverageReport cov)
    {
        Section(sb, "unused-steps", "Unused step definitions",
            $"Coverage {cov.CoveragePercentage:F1}% · {cov.UsedStepDefinitions}/{cov.TotalStepDefinitions} bindings used · {cov.UnusedDefinitions.Count} unused");
        if (cov.UnusedDefinitions.Count == 0) { Empty(sb, "Every step definition is used by at least one scenario."); return; }

        sb.Append("<table><thead><tr><th>Kind</th><th>Pattern</th><th>Method</th><th>Location</th></tr></thead><tbody>");
        foreach (var d in cov.UnusedDefinitions)
        {
            sb.Append("<tr>");
            sb.Append($"<td><span class=\"tag\">{E(d.Type.ToString())}</span></td>");
            sb.Append($"<td class=\"mono\">{E(d.Pattern)}</td>");
            sb.Append($"<td class=\"mono dim\">{E(d.ClassName)}.{E(d.MethodName)}</td>");
            sb.Append($"<td class=\"mono dim\">{E(ShortPath(d.FilePath))}:{d.LineNumber}</td>");
            sb.Append("</tr>");
        }
        sb.Append("</tbody></table></section>");
    }

    private static void AppendDataErrors(StringBuilder sb, DuplicateAnalysisReport r)
    {
        Section(sb, "data-errors", "Data errors", $"{r.DataErrors.Count} feature-file issue(s)");
        if (r.DataErrors.Count == 0) { Empty(sb, "No data errors."); return; }

        foreach (var group in r.DataErrors.GroupBy(e => e.ErrorType))
        {
            sb.Append($"<h3>{E(Humanize(group.Key.ToString()))} <span class=\"count\">{group.Count()}</span></h3>");
            sb.Append("<table><thead><tr><th>Scenario</th><th>Detail</th><th>Location</th></tr></thead><tbody>");
            foreach (var e in group)
            {
                var detail = e.UndefinedPlaceholders.Count > 0
                    ? "Undefined: " + string.Join(", ", e.UndefinedPlaceholders.Select(p => "&lt;" + E(p) + "&gt;"))
                    : E(e.StepText);
                sb.Append("<tr>");
                sb.Append($"<td>{E(e.Scenario)}</td>");
                sb.Append($"<td class=\"mono\">{detail}</td>");
                sb.Append($"<td class=\"mono dim\">{E(e.FeatureFile)}:{e.LineNumber}</td>");
                sb.Append("</tr>");
            }
            sb.Append("</tbody></table>");
        }
        sb.Append("</section>");
    }

    private static void AppendDuplicates(StringBuilder sb, DuplicateAnalysisReport r)
    {
        var stepDupes = r.CrossProjectDuplicates.Concat(r.WithinProjectDuplicates).ToList();
        Section(sb, "duplicates", "Duplicate scenarios & steps",
            $"{r.ScenarioDuplicates.Count} duplicate scenario group(s) · {stepDupes.Count} duplicated step(s)");

        if (r.ScenarioDuplicates.Count == 0 && stepDupes.Count == 0) { Empty(sb, "No duplicates found."); return; }

        if (r.ScenarioDuplicates.Count > 0)
        {
            sb.Append("<h3>Scenario duplicates</h3>");
            sb.Append("<table><thead><tr><th>Type</th><th>Scenario</th><th>Overlaps with</th><th>%</th></tr></thead><tbody>");
            foreach (var g in r.ScenarioDuplicates)
                foreach (var m in g.Matches)
                {
                    sb.Append("<tr>");
                    sb.Append($"<td><span class=\"tag\">{E(g.DuplicateType.ToString())}</span></td>");
                    sb.Append($"<td>{E(g.BaseScenario.ScenarioName)} <span class=\"dim mono\">({E(g.BaseScenario.FeatureFile)}:{g.BaseScenario.ScenarioLineNumber})</span></td>");
                    sb.Append($"<td>{E(m.Scenario.ScenarioName)} <span class=\"dim mono\">({E(m.Scenario.FeatureFile)}:{m.Scenario.ScenarioLineNumber})</span></td>");
                    sb.Append($"<td>{m.OverlapPercentage:F0}%</td>");
                    sb.Append("</tr>");
                }
            sb.Append("</tbody></table>");
        }

        if (stepDupes.Count > 0)
        {
            sb.Append("<h3>Duplicated steps</h3>");
            sb.Append("<table><thead><tr><th>Step</th><th>Occurrences</th></tr></thead><tbody>");
            foreach (var g in stepDupes)
            {
                sb.Append("<tr>");
                sb.Append($"<td class=\"mono\">{E(g.StepPattern)}</td>");
                sb.Append($"<td>{g.Occurrences.Count}</td>");
                sb.Append("</tr>");
            }
            sb.Append("</tbody></table>");
        }
        sb.Append("</section>");
    }

    // --- helpers ---

    private static void Section(StringBuilder sb, string id, string title, string sub)
        => sb.Append($"<section id=\"{id}\"><h2>{E(title)}</h2><p class=\"sub\">{E(sub)}</p>");

    private static void Empty(StringBuilder sb, string msg)
        => sb.Append($"<p class=\"empty\">✓ {E(msg)}</p></section>");

    private static string E(string? s) => WebUtility.HtmlEncode(s ?? "");

    private static string ShortPath(string path)
    {
        if (string.IsNullOrEmpty(path)) return "";
        var parts = path.Replace('\\', '/').Split('/');
        return parts.Length <= 2 ? path : string.Join("/", parts[^2..]);
    }

    private static string Humanize(string pascal)
    {
        var sb = new StringBuilder();
        for (int i = 0; i < pascal.Length; i++)
        {
            if (i > 0 && char.IsUpper(pascal[i])) sb.Append(' ');
            sb.Append(i == 0 ? char.ToUpperInvariant(pascal[i]) : char.ToLowerInvariant(pascal[i]));
        }
        return sb.ToString();
    }

    private const string Css = """
        :root { --bg:#0f1420; --panel:#171d2b; --line:#26304a; --txt:#e6e9f0; --dim:#8a94ab;
                --accent:#4dabf7; --ok:#37b24d; --warn:#f59f00; --bad:#e64980; }
        * { box-sizing:border-box; }
        body { margin:0; background:var(--bg); color:var(--txt);
               font:15px/1.5 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif; }
        header,section,footer { max-width:1100px; margin:0 auto; padding:0 24px; }
        header { padding-top:40px; }
        h1 { margin:0; font-size:28px; letter-spacing:-.5px; }
        h2 { margin:0 0 4px; font-size:20px; }
        h3 { margin:24px 0 8px; font-size:15px; color:var(--dim); text-transform:uppercase; letter-spacing:.5px; }
        h3 .count { color:var(--txt); background:var(--line); border-radius:10px; padding:1px 8px; font-size:12px; }
        .sub { color:var(--dim); margin:4px 0 0; }
        .cards { display:grid; grid-template-columns:repeat(auto-fit,minmax(160px,1fr)); gap:14px; margin:24px 0 8px; }
        .card { background:var(--panel); border:1px solid var(--line); border-left-width:4px; border-radius:10px; padding:16px; display:flex; flex-direction:column; }
        .card .n { font-size:30px; font-weight:700; }
        .card .l { color:var(--dim); font-size:13px; }
        .card.ok { border-left-color:var(--ok); } .card.warn { border-left-color:var(--warn); } .card.bad { border-left-color:var(--bad); }
        section { margin-top:44px; }
        table { width:100%; border-collapse:collapse; margin-top:12px; font-size:13.5px; overflow-x:auto; display:block; }
        thead th { text-align:left; color:var(--dim); font-weight:600; border-bottom:1px solid var(--line); padding:8px 10px; white-space:nowrap; }
        tbody td { padding:8px 10px; border-bottom:1px solid var(--line); vertical-align:top; }
        tbody tr:hover { background:rgba(255,255,255,.02); }
        .mono { font-family:ui-monospace,SFMono-Regular,Consolas,monospace; font-size:12.5px; }
        .dim { color:var(--dim); }
        .tag { background:var(--line); color:var(--accent); border-radius:6px; padding:2px 7px; font-size:11px; font-weight:600; }
        .empty { color:var(--ok); background:var(--panel); border:1px solid var(--line); border-radius:10px; padding:16px; margin-top:12px; }
        footer { color:var(--dim); font-size:12.5px; text-align:center; margin:60px auto 40px; padding-top:20px; border-top:1px solid var(--line); }
        @media (prefers-color-scheme:light) {
          :root { --bg:#f7f8fa; --panel:#fff; --line:#e2e6ee; --txt:#1a2030; --dim:#6b7488; }
          tbody tr:hover { background:rgba(0,0,0,.02); }
        }
        """;
}
